language: generic
sudo: required
services:
    - docker

# This is the step to mention the command to create the docker image
before_install:
    - docker build -t anandsivaji/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true anandsivaji/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-574322318218"
    bucket_path: "docker-react"
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY
            